name: workflow-package-build-manual

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Enter AUR package to build'
        required: true
        default: 'htpasswd,libtorrent-rasterbar-1_2-git,python2-bin'

jobs:
  package-build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_PATH: "${GITHUB_WORKSPACE}/compiled/amd64"
      AUR_PACKAGES: "${{ github.event.inputs.package_name }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU for multi-arch support
        uses: docker/setup-qemu-action@v3
      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: DEBUG Show Runners environment
        shell: bash
        run: |
          export
      - name: Download AUR package tarball
        shell: bash
        run: |
          cd /tmp || exit 1

          # get package version from PKGBUILD file
          for package in ${{ env.AUR_PACKAGES }}; do
            # download tarball and extract
            if ! stderr=$(curl --max-time 600 --retry-max-time 600 --retry 12 --retry-delay 10 --connect-timeout 5 -o "${package}.tar.gz" -L "https://aur.archlinux.org/cgit/aur.git/snapshot/${package}.tar.gz" && tar -xvf "${package}.tar.gz" -C .); then
              echo "[error] Failed to download AUR package snapshot '${package}' from AUR, error is '${stderr}'" >&2
              exit 1
            fi
          done
      - name: Identify package names and versions from extracted tarball file 'PKGBUILD' and save to $GITHUB_ENV
        shell: bash
        run: |
          cd /tmp || exit 1

          for package in ${{ env.AUR_PACKAGES }}; do
            if [[ -f "./${package}/PKGBUILD" ]]; then
              source "./${package}/PKGBUILD"

              # extract package name and version variables from PKGBUILD
              pkgname="${pkgname}"
              pkgver="${pkgver}-${pkgrel}"

              # show details for debug
              echo "[debug] AUR Package '${package}' name is '${pkgname}'"
              echo "[debug] AUR Package '${package}' version is '${pkgver}'"

              # Save to GitHub environment for use in subsequent steps
              echo "${package}=${pkgname},${pkgver}" >> "${GITHUB_ENV}"
            else
              echo "[warn] PKGBUILD file not found for package '${package}'" >&2
            fi
          done
      - name: Compare version in .version file to pkg_ver from PKGBUILD file and filter packages
        shell: bash
        run: |
          cd /tmp || exit 1

          # Convert comma-separated list to array
          IFS=',' read -ra package_array <<< "${{ env.AUR_PACKAGES }}"
          packages_to_build=()

          # process each package
          for package in "${package_array[@]}"; do
            # Get the package name from environment variable (format: "name,version")
            package_info=$(printenv "${package}" 2>/dev/null || echo "")
            if [[ -n "${package_info}" ]]; then
              IFS=',' read -r pkg_name pkg_version <<< "${package_info}"

              # Compare the version in the .version file to the pkgver from PKGBUILD
              if [[ -f "${{ env.PACKAGE_PATH }}/${pkg_name}-x86_64.pkg.tar.zst.version" ]]; then
                existing_version=$(cat "${{ env.PACKAGE_PATH }}/${pkg_name}-x86_64.pkg.tar.zst.version" 2>/dev/null || echo "")
                if [[ "${existing_version}" == "${pkg_version}" ]]; then
                  echo "[info] Package '${pkg_name}' version '${pkg_version}' is already built and up-to-date, skipping adding to build list"
                else
                  echo "[info] Package '${pkg_name}' version '${pkg_version}' is different to existing version '${existing_version}', adding to build list"
                  packages_to_build+=("${package}")
                fi
              else
                echo "[info] No existing version file found for package '${pkg_name}', adding to build list"
                packages_to_build+=("${package}")
              fi
            fi
          done

          # Create new comma-separated list of packages to build
          IFS=',' eval 'filtered_packages="${packages_to_build[*]}"'
          echo "FILTERED_AUR_PACKAGES=${filtered_packages}" >> "${GITHUB_ENV}"
          echo "[debug] Original packages: ${{ env.AUR_PACKAGES }}"
          echo "[debug] Filtered packages to build: ${filtered_packages}"

          # Exit entire workflow if no packages need to be built
          if [[ -z "${filtered_packages}" ]]; then
            echo "[info] No packages need to be built, all are up-to-date. Exiting workflow."
            exit 0
          fi
      - name: Build AUR packages using docker image binhex/arch-devel
        shell: bash
        run: |
          cd /tmp || exit 1

          # ensure we have no pre-existing packages, as github re-uses executors
          rm -f *.tar.zst

          echo "Package(s) to build: ${{ env.FILTERED_AUR_PACKAGES }}"
          docker pull binhex/arch-devel:latest
          docker run -v $(pwd):/host -t binhex/arch-devel bash -c "refresh.sh && aur.sh --aur-package '${{ env.FILTERED_AUR_PACKAGES }}' --package-path '/host'"
      - name: DEBUG Showing compiled package(s) on host filesystem
        shell: bash
        run: |
          cd /tmp || exit 1

          echo "[debug] Working in directory: $(pwd)"
          if ! ls -la *.tar.zst 2>/dev/null; then
            echo "[info] No tar.zst files found - no packages were built, exiting workflow"
            exit 0
          fi
      - name: Move with rename compiled package to GitHub repository workspace
        shell: bash
        run: |
          cd /tmp || exit 1

          # fix ownership of the compiled packages and destination directory
          sudo chown -R $(id -u):$(id -g) *.tar.zst "${{ env.PACKAGE_PATH }}"

          # Convert comma-separated list to array for the filtered packages
          IFS=',' read -ra filtered_package_array <<< "${{ env.FILTERED_AUR_PACKAGES }}"

          # move packages to GitHub workspace with correct naming format
          for package in "${filtered_package_array[@]}"; do
            # Get the package name from environment variable (format: "name,version")
            package_info=$(printenv "${package}" 2>/dev/null || echo "")
            if [[ -n "${package_info}" ]]; then
              IFS=',' read -r pkg_name pkg_version <<< "${package_info}"

              # Find the compiled package file that matches this package
              for filepath in *.tar.zst; do
                if [[ "${filepath}" == "${pkg_name}"* ]]; then
                  final_name="${pkg_name}-x86_64.pkg.tar.zst"
                  echo "[info] Moving '${filepath}' to '${{ env.PACKAGE_PATH }}/${final_name}'"
                  mv "${filepath}" "${{ env.PACKAGE_PATH }}/${final_name}"
                  echo "[info] Writing package version to file '${{ env.PACKAGE_PATH }}/${final_name}.version'"
                  echo "${pkg_version}" > "${{ env.PACKAGE_PATH }}/${final_name}.version"
                  break
                fi
              done
            fi
          done
      - name: Commit and push packages to currently checked out GitHub repository
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add "${{ env.PACKAGE_PATH }}/"*
          if git commit -m "Added compiled AUR package(s) that were built: ${{ env.FILTERED_AUR_PACKAGES }}"; then
            git push
            echo "Pushed compiled package(s) to GitHub repository."
          else
            echo "No changes to commit."
          fi
