name: workflow-package-build-manual

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Enter AUR package to build'
        required: true
        default: ''

jobs:
  package-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU for multi-arch support
        uses: docker/setup-qemu-action@v3
      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: DEBUG Show Runners environment
        shell: bash
        run: |
            export
      - name: Build AUR packages
        shell: bash
        run: |
            echo "Package(s) to build: ${{ github.event.inputs.package_name }}"
            docker pull binhex/arch-devel:latest
            docker run -v /tmp:/host -t binhex/arch-devel bash -c "aur.sh --aur-package '${{ github.event.inputs.package_name }}' --package-path '/host'"
