name: workflow-package-build-schedule

on:
  schedule:
    # run at midnight every day
    - cron: "0 0 * * *"
  push:
    tags:
      - '*'

jobs:
  package-build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_PATH: "${GITHUB_WORKSPACE}/packages/compiled/amd64"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU for multi-arch support
        uses: docker/setup-qemu-action@v3
      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: DEBUG Show Runners environment
        shell: bash
        run: |
            export
      - name: Build AUR packages
        shell: bash
        run: |
            echo "Package(s) to build: ${{ github.event.inputs.package_name }}"
            docker pull binhex/arch-devel:latest
            docker run -v "${{ env.PACKAGE_PATH }}":/host -t binhex/arch-devel bash -c "refresh.sh && aur.sh --aur-package '${{ github.event.inputs.package_name }}' --package-path '/host'"
      - name: DEBUG Showing compiled package(s) on host filesystem
        shell: bash
        run: |
            ls -al "${{ env.PACKAGE_PATH }}"
      - name: Commit and push packages to currently checked out GitHub repository
        shell: bash
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add "${{ env.PACKAGE_PATH }}/"*.tar.zst
            if git commit -m "Added compiled AUR package(s): ${{ github.event.inputs.package_name }}"; then
              git push
              echo "Pushed compiled package(s) to GitHub repository."
            else
              echo "No changes to commit."
            fi
