name: workflow-package-build-manual

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Enter AUR package to build'
        required: true
        default: 'htpasswd,libtorrent-rasterbar-1_2-git'

jobs:
  package-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU for multi-arch support
        uses: docker/setup-qemu-action@v3
      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: DEBUG Show Runners environment
        shell: bash
        run: |
            export
      - name: Build AUR packages
        shell: bash
        run: |
            echo "Package(s) to build: ${{ github.event.inputs.package_name }}"
            docker pull binhex/arch-devel:latest
            docker run -v "${GITHUB_WORKSPACE}/packages/compiled/amd64":/host -t binhex/arch-devel bash -c "refresh.sh && aur.sh --aur-package '${{ github.event.inputs.package_name }}' --package-path '/host'"
      - name: DEBUG Showing compiled package(s) on host filesystem
        shell: bash
        run: |
            ls -al "${GITHUB_WORKSPACE}/packages/compiled/amd64"
      - name: Commit and push packages to currently checked out GitHub repository
        shell: bash
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add "${GITHUB_WORKSPACE}/packages/compiled/amd64/"*.tar.zst
            if git commit -m "Added compiled AUR package(s): ${{ github.event.inputs.package_name }}"; then
              git push
              echo "Pushed compiled package(s) to GitHub repository."
            else
              echo "No changes to commit."
            fi
